"""Compatibility imports for optional QschEditor-backed schematic services."""

from __future__ import annotations

from .schematic_editor_backend import (
    _GROUND_NET_NAME,
    ComponentSymbolMetadata,
    SimpleComponentKind,
    SymbolDrawingMetadata,
    SymbolPinMetadata,
    SymbolTextMetadata,
    _QschEditorFactory,
    _QschEditorProtocol,
    _SchematicComponentProtocol,
    component_rotation_degrees_to_index,
    component_rotation_index_to_degrees,
    load_qsch_editor_factory,
    normalize_component_parameters,
    normalize_component_position,
    normalize_component_rotation,
    open_schematic_editor,
    resolve_schematic_output_path,
)
from .schematic_editor_edits import (
    add_component_symbol_drawing_metadata,
    add_dll_block,
    add_dll_block_pin_metadata,
    add_junction,
    add_net_label,
    add_simple_component,
    add_wire,
    bootstrap_blank_schematic,
    create_blank_schematic_file,
    read_component_symbol_metadata,
    remove_component_symbol_drawing_metadata,
    remove_dll_block_pin_metadata,
    remove_junction,
    remove_net_label,
    remove_wire,
    set_component_position,
    set_component_rotation,
    set_component_symbol_drawing_metadata,
    set_component_symbol_pin_metadata,
    set_component_symbol_text_attributes,
    set_dll_block_pin_role_metadata,
)
from .schematic_editor_geometry import resolve_component_pin_position, resolve_wire_points

__all__ = [
    "_GROUND_NET_NAME",
    "ComponentSymbolMetadata",
    "SimpleComponentKind",
    "SymbolDrawingMetadata",
    "SymbolPinMetadata",
    "SymbolTextMetadata",
    "_QschEditorFactory",
    "_QschEditorProtocol",
    "_SchematicComponentProtocol",
    "add_component_symbol_drawing_metadata",
    "add_dll_block",
    "add_dll_block_pin_metadata",
    "add_junction",
    "add_net_label",
    "add_simple_component",
    "add_wire",
    "bootstrap_blank_schematic",
    "component_rotation_degrees_to_index",
    "component_rotation_index_to_degrees",
    "create_blank_schematic_file",
    "load_qsch_editor_factory",
    "normalize_component_parameters",
    "normalize_component_position",
    "normalize_component_rotation",
    "open_schematic_editor",
    "read_component_symbol_metadata",
    "remove_component_symbol_drawing_metadata",
    "remove_dll_block_pin_metadata",
    "remove_junction",
    "remove_net_label",
    "remove_wire",
    "resolve_component_pin_position",
    "resolve_schematic_output_path",
    "resolve_wire_points",
    "set_component_position",
    "set_component_rotation",
    "set_component_symbol_drawing_metadata",
    "set_component_symbol_pin_metadata",
    "set_component_symbol_text_attributes",
    "set_dll_block_pin_role_metadata",
]
